<?php
/**
 * Zapcel WHMCS - English Language File
 *
 * @package    Zapcel
 * @author     Hostcel
 * @version    2.0.0
 */
return [
    // General
    'module_name' => 'Zapcel WHMCS',
    'module_description' => 'WhatsApp notification system',
    'welcome' => 'Welcome to Zapcel',
    'save' => 'Save', 
    'cancel' => 'Cancel',
    'back' => 'Back',
    'edit' => 'Edit',
    'delete' => 'Delete',
    'activate' => 'Activate',
    'deactivate' => 'Deactivate',
    'active' => 'Active',
    'inactive' => 'Inactive',
    'status' => 'Status',
    'actions' => 'Actions',
    'search' => 'Search',
    'filter' => 'Filter',
    'refresh' => 'Refresh',
    'clear' => 'Clear',
    'export' => 'Export',
    'import' => 'Import',
    'download' => 'Download',
    'upload' => 'Upload',
    'confirm' => 'Confirm',
    'success' => 'Success',
    'error' => 'Error',
    'warning' => 'Warning',
    'info' => 'Information',
    'loading' => 'Loading',
    'response_log' => 'Response',
    
    // Dashboard
    'dashboard' => 'Dashboard',
    'dashboard_title' => 'Zapcel WHMCS - Dashboard',
    'dashboard_subtitle' => 'WhatsApp notification system control panel',
    'total_messages' => 'Total Messages',
    'success_rate' => 'Success Rate',
    'successful_messages' => 'Successful Messages',
    'failed_messages' => 'Failed Messages',
    'templates' => 'Templates',
    'active_templates' => 'active',
    'whatsapp_validated' => 'WhatsApp Validated',
    'clients_with_whatsapp_verified' => 'Clients with WhatsApp verified',
    'today' => 'Today',
    'recent_messages' => 'Recent Messages',
    'client' => 'Client',
    'event' => 'Event',
    'date' => 'Date',
    'all' => 'All',
    'events' => 'Events',
    'no_messages_sent' => 'No messages sent yet',
    'system_status' => 'System Status',
    'database' => 'Database',
    'whatsapp_api' => 'WhatsApp API',
    'active_hooks' => 'Active Hooks',
    'connected' => 'Connected',
    'disconnected' => 'Disconnected',
    'quick_actions' => 'Quick Actions',
    'manage_templates' => 'Templates',
    'manage_gateways' => 'Gateways',
    'validations' => 'Validations',
    'view_logs' => 'Logs',
    'test_message' => 'Test Message',
    'settings' => 'Settings',
    'debug_logging' => 'Debug Logging',
    'debug_logging_tooltip' => 'Detailed logs of system actions. Recommended only for troubleshooting.',
    'debug_enabled_tooltip' => 'Detailed logs active',
    'debug_disabled_tooltip' => 'Only essential logs',
    'enabled' => 'Enabled',
    'disabled' => 'Disabled',
    'system' => 'System',
    'developer' => 'By',
    'quick_reply_badge' => 'Quick Reply',
    
    // Templates
    'manage_message_templates' => 'Manage Message Templates',
    'templates_subtitle' => 'Configure automatic WhatsApp messages',
    'template_name' => 'Template Name',
    'trigger_event' => 'Trigger Event',
    'usage' => 'Usage',
    'last_update' => 'Last Update',
    'new_template' => 'New Template',
    'no_templates_found' => 'No templates found',
    'create_first_template' => 'Create First Template',
    'create_template' => 'Create Template',
    'select_event' => 'Select an event...',
    'invoice_created' => 'Invoice Created',
    'invoice_reminder' => 'Invoice Reminder',
    'invoice_paid' => 'Invoice Paid',
    'invoice_cancelled' => 'Invoice Cancelled',
    'invoice_reminder_1' => '1st Invoice Reminder',
    'invoice_reminder_2' => '2nd Invoice Reminder',
    'invoice_reminder_3' => '3rd Invoice Reminder',
    'ticket_created' => 'Ticket Created',
    'ticket_opened' => 'Ticket Opened',
    'ticket_replied' => 'Ticket Replied',
    'ticket_reply' => 'Ticket Reply',
    'service_activated' => 'Service Activated',
    'service_suspended' => 'Service Suspended',
    'service_unsuspended' => 'Service Unsuspended',
    'service_terminated' => 'Service Terminated',
    'cancellation_request' => 'Cancellation Request',
    'client_added' => 'Client Added',
    'client_edited' => 'Client Edited',
    'password_changed' => 'Password Changed',
    'quote_created' => 'Quote Created',
    'quote_modified' => 'Quote Modified',
    'quote_accepted' => 'Quote Accepted',
    'email_presend' => 'Email Replacement',
    'email_replaced' => 'Email Replaced',
    'whatsapp_validation' => 'WhatsApp Validation',
    'message_template' => 'Message Template',
    'enter_message_template' => 'Enter the message template...',
    'use_variables_in_braces' => 'Use variables in braces {example}. Select text and click buttons to format.',
    'available_variables' => 'Available variables',
    'general_variables' => 'General',
    'invoice_variables' => 'Invoices',
    'ticket_variables' => 'Tickets',
    'edit_template' => 'Edit Template',
    'edit_template_subtitle' => 'Modify WhatsApp message template',
    'event_cannot_be_changed' => 'Event cannot be changed after creation',
    'template_statistics' => 'Statistics',
    'created_at' => 'Created at',
    'updated_at' => 'Updated at',
    'cpf_cnpj_var' => 'Client CPF',
    
    // Statistics
    'detailed_statistics' => 'Detailed Statistics',
    'statistics_subtitle' => 'Complete system reports and analytics',
    'period' => 'Period',
    'day' => 'Today',
    'week' => 'This Week',
    'month' => 'This Month',
    'year' => 'This Year',
    'statistics_by_event_type' => 'Statistics by Event Type',
    'total' => 'Total',
    'rate' => 'Rate',
    
    // Validation
    'whatsapp_validation_title' => 'WhatsApp Validation',
    'validation_subtitle' => 'Manage client WhatsApp number validation',
    'total_clients' => 'Total Clients',
    'validated' => 'Validated',
    'pending' => 'Pending',
    'blocked' => 'Blocked',
    'invalidated' => 'Invalidated',
    'validation_history' => 'Filter Validations',
    'phone' => 'Phone',
    'code' => 'Code',
    'attempts' => 'Attempts',
    'last_attempt' => 'Last Attempt',
    'send_pending' => 'Send Pending',
    'resend_code' => 'Resend Code',
    'view_details' => 'View Details',
    'reset_validation' => 'Reset Validation',
    'validation_details' => 'Validation Details',
    'not_started' => 'Not Started',
    'search_client' => 'Enter your search...',
    'close' => 'Close',
    'validation_code_resent_success' => 'Validation code resent successfully!',
    'send_code_failed' => 'Failed to send verification code',
    'log_validation_code_sent' => 'Verification code sent',
    'validation_code_sent_success' => 'Verification code sent successfully',
    'log_send_code_failed_prefix' => 'Failed to send code:',
    'validation_not_found' => 'No pending validation found',
    'validation_already_processed' => 'Validation has already been processed',
    'code_expired_request_new' => 'Code expired. Please request a new code.',
    'too_many_attempts_blocked' => 'Number blocked due to too many failed attempts',
    'invalid_code_attempts_left' => 'Invalid code. {attempts} attempts remaining.',
    'log_whatsapp_validated' => 'WhatsApp successfully validated',
    'whatsapp_validated_success' => 'WhatsApp successfully validated!',
    'log_validation_failed_prefix' => 'Verification failed:',
    'validation_not_started' => 'Validation not started',
    'validation_none_found' => 'No validation found',
    'resend_code_failed' => 'Failed to resend code',
    'log_code_resent' => 'Code resent',
    'code_resent_success' => 'Code resent successfully',
    'log_resend_failed_prefix' => 'Resend failed:',
    'log_phone_updated_whmcs' => 'Phone number updated in WHMCS',
    'log_phone_update_error' => 'Error updating phone number',
    'phone_update_error' => '❌ Phone Update Error',
    'validation_template_default' => "▫️ *WhatsApp Validation* ▫️

Hello! ➡️ 

To confirm your WhatsApp number and receive our notifications, use the code below:

⚡ *Verification Code:* `{codigo_validacao}`

This code expires in 15 minutes.

⚠️ *Do not share this code with anyone.*

Best regards,
*{provedor}*",
    'provider_default_name' => 'Our Provider',
    'log_validation_reset' => 'Validation reset',
    'validation_reset_success' => 'Validation reset successfully',
    'total_clients_desc' => 'Clients with a validation attempt.',
    'validated_desc' => 'WhatsApp successfully confirmed.',
    'pending_desc' => 'Awaiting code confirmation.',
    'invalidated_desc' => 'Expired, invalid, or blocked codes.',
    'validation_failed' => '❌ Validation Failed',
    'phone_updated' => '☎️ Phone Updated',
    'validation_completed' => '⭐ Validation Completed',
    'validation_sent' => '✅ Validation Sent',
    'validation_code_sent' => '✅ Code Sent',
    'validation_resent' => '✔️ Validation Resent',
    
    // Gateways
    'payment_gateways' => 'Payment Gateways',
    'gateways_subtitle' => 'Configure gateways for PIX and boleto extraction',
    'installed' => 'Installed',
    'not_installed' => 'Not Installed',
    'last_sync' => 'Last Sync',
    'never' => 'Never',
    'configure' => 'Configure',
    'remove' => 'Remove',
    'install_gateway' => 'Install Gateway',
    'supported_features' => 'Supported Features',
    'how_it_works' => 'How It Works',
    'automatic_pix_extraction' => 'Automatic PIX code extraction (copy and paste)',
    'qrcode_generation' => 'PIX QR Code generation',
    'barcode_extraction' => 'Boleto barcode extraction',
    'pdf_download' => 'Boleto PDF download',
    'automatic_status_sync' => 'Automatic status synchronization',
    'gateways_integration_info' => 'Gateways automatically integrate with WHMCS invoices and extract payment information for WhatsApp sending.',
    'tip_activate_used_gateways' => 'Tip: Only activate gateways you use in your WHMCS.',
    
    // Logs
    'system_logs' => 'System Logs',
    'logs_subtitle' => 'Complete record of all system activities',
    'clear_logs' => 'Clear Logs',
    'date_time' => 'Date/Time',
    'event_type' => 'Type',
    'message' => 'Message',
    'details' => 'Details',
    'all_types' => 'All Types',
    'date_from' => 'From',
    'date_to' => 'To',
    'view_more' => 'view more',
    'log_details' => 'Log Details',
    'showing_records' => 'Showing %s of %s records',
    'filters' => 'Filters',
    
    // Settings
    'zapcel_settings' => 'Zapcel Settings',
    'settings_subtitle' => 'Configure main module options',
    'save_settings' => 'Save Settings',
    'main_settings' => 'Main Settings',
    'module_status' => 'Module Status',
    'activate_deactivate_module' => 'Activate or deactivate Zapcel module completely',
    'instance_id' => 'Instance ID',
    'enter_instance_id' => 'Enter Zapcel instance ID',
    'instance_id_help' => 'Zapcel instance ID',
    'access_token' => 'Access Token',
    'enter_access_token' => 'Enter Zapcel API access token',
    'access_token_help' => 'Zapcel API access token',
    'message_delay' => 'Message Delay (seconds)',
    'message_delay_help' => 'Wait time between messages to avoid blocks',
    'max_attempts' => 'Max Attempts',
    'max_attempts_help' => 'Maximum number of attempts to send a message',
    'validation_template' => 'Validation Template',
    'select_template' => 'Select a template...',
    'module_language' => 'Module Language',
    'portuguese_brazil' => 'Português (Brasil)',
    'english' => 'English',
    'enable_logging' => 'Enable detailed logging',
    'enable_logging_help' => 'Recommended for system debug and monitoring',
    'log_retention_days' => 'Days to Keep Logs',
    'log_retention_days_help' => 'Older logs will be automatically deleted',
    'connection_status' => 'Connection Status',
    'test_connection' => 'Test Connection',
    'account_info' => 'Account Information',
    'phone_number' => 'Number',
    'instance_name' => 'Instance',
    'battery' => 'Battery',
    'platform' => 'Platform',
    'connect_to_api' => 'Connect to API to see account information',
    'quick_actions_settings' => 'Quick Actions',
    'clear_cache' => 'Clear Cache',
    'sync_templates' => 'Sync Templates',
    'export_settings' => 'Export Settings',
    'confirm_clear_cache' => 'Confirm cache clearance',
    'clear_cache_warning' => 'This will empty the templates cache. Statistics and logs will NOT be affected.',
    'cache_templates_cleared' => 'Templates cache cleared successfully!',
    'clear_cache_templates' => 'Clear Templates Cache',
    'cache_cleared_success' => 'Cache cleared successfully!',
    'cache_clear_error' => 'Error clearing cache',
    'cache_management' => 'Cache Management',
    'settings_imported_by_admin' => 'Settings imported by administrator',
    'settings_exported_by_admin' => 'Settings exported by administrator', 
    'cache_cleared_by_admin' => 'Cache cleared by administrator',
    'test_message_sent_by_admin' => 'Test message sent by administrator',
    'import_settings' => 'Import Settings', 
    'import_success' => 'Settings imported successfully!',
    'invalid_file_format' => 'Invalid file format. Use only JSON files.',
    'select_file_to_import' => 'Select file to import',
    'import_settings_warning' => 'This will replace current settings. Are you sure?',
    'enable_floating_button' => 'Enable Floating WhatsApp Button',
    'enable_floating_button_help' => 'Displays a floating WhatsApp button in the client area',
    'company_phone_number' => 'Company Phone Number (WhatsApp)', 
    'company_phone_number_help' => 'Number in international format (ex: +1 (555) 123-4567 for Brazil). If empty, disables the button.',
    'hide_mobile_button' => 'Hide Button on Mobile Devices',
    'hide_mobile_button_help' => 'Hides the floating button on smartphones and tablets',
    'enable_validation_system' => 'Mandatory WhatsApp Validation',
    'enable_validation_system_help' => 'Client must validate WhatsApp to access client area',
    'require_validation' => 'Send messages only to validated numbers',
    'require_validation_help' => 'If checked, will only send messages to clients with validated WhatsApp',
    "autologin_domain" => "Link Shortener",
    "autologin_domain_help" => "Optional domain alias (ex: https://hcel.ink/central/) to create a shortened autologin URL.",

    // Test Message
    'test_whatsapp_message' => 'Test WhatsApp Message',
    'test_message_subtitle' => 'Send test messages to verify configuration',
    'configure_test_message' => 'Configure Test Message',
    'destination_client' => 'Destination Client',
    'select_client' => 'Select a client...',
    'test_message_content' => 'Test Message',
    'enter_test_message' => 'Enter your test message here... You can use variables: {client} and {provider}',
    'available_variables_test' => 'Available variables: {client} (client name) and {provider} (company name)',
    'simulate_only' => 'Only simulate sending (do not actually send)',
    'simulate_only_help' => 'Uncheck this option to send real message via WhatsApp',
    'send_test_message' => 'Send Test Message',
    'message_preview' => 'Message Preview',
    'select_template_or_type' => 'Select a template or type a message to see preview',
    'available_variables_list' => 'Available Variables',
    'use_variables_below' => 'Use the variables below in your message. They will be automatically replaced with actual data from the selected client.',
    'client_full_name' => 'Client full name',
    'company_name' => 'Your company name',
    'test_variables_tip' => 'Tip: To test messages with invoice or ticket variables, use templates configured in the Templates page.',
    'test_result' => 'Test Result',
    'message_preview_title' => 'Message Preview',
    'recipient' => 'Recipient',
    'simulation_mode' => 'Simulation mode: Message was not sent (preview only)',
    'message_sent_successfully' => 'Message sent successfully!',
    
    // Variables - Clean descriptions without redundancy
    'variables' => 'Variables',
    'general_category' => 'General',
    'invoices' => 'Invoices',
    'tickets' => 'Tickets',
    'clients' => 'Clients',
    'services' => 'Services',
    'cancellations' => 'Cancellations',
    'quotes' => 'Quotes',
    
    // General Variables
    'client_var' => 'Client full name',
    'provider_var' => 'Provider/company name',
    'break_message_var' => 'Send message into parts',
    'signature_var' => 'Signature configured in messages',
    'whmcs_url_var' => 'Complete WHMCS system URL',
    'current_date_var' => 'Current date in dd/mm/yyyy format',
    'current_time_var' => 'Current time in HH:MM format',
    'current_datetime_var' => 'Complete current date and time',
    
    // Client Variables
    'client_id_var' => 'Client numeric ID in system',
    'client_firstname_var' => 'Client first name',
    'client_lastname_var' => 'Client last name',
    'client_email_var' => 'Client email address',
    'client_phone_var' => 'Client phone number',
    'client_address_var' => 'Client complete address',
    'client_neighborhood_var' => 'Client neighborhood',
    'client_city_var' => 'Client city',
    'client_state_var' => 'Client state',
    'client_zipcode_var' => 'Client ZIP code',
    'client_country_var' => 'Client country',
    
    // Invoice Variables
    'invoice_number_var' => 'Invoice number',
    'title_var' => 'Invoice title',
    'value_var' => 'Total amount',
    'due_date_var' => 'Due date',
    'days_until_due_var' => 'Days until due (e.g., "today", "tomorrow", "5 days")',
    'creation_date_var' => 'Invoice creation date',
    'payment_date_var' => 'Invoice payment date',
    'cancellation_date_var' => 'Invoice cancellation date',
    'pix_code_var' => 'PIX payment code',
    'qr_code_url_var' => 'PIX QR Code image URL',
    'barcode_var' => 'Boleto barcode line',
    'invoice_link_var' => 'Link to view invoice',
    'invoice_items_var' => 'List of invoice items',
    'payment_method_var' => 'Payment method used',
    'cancellation_reason_var' => 'Invoice cancellation reason',
    
    // Ticket Variables
    'ticket_number_var' => 'Ticket number',
    'subject_var' => 'Ticket subject',
    'ticket_message_var' => 'Ticket message',
    'department_var' => 'Ticket department',
    'priority_var' => 'Ticket priority (Low, Medium, High, Critical)',
    'admin_name_var' => 'Name of staff who replied',
    'ticket_link_var' => 'Link to view ticket',
    
    // Service Variables
    'service_name_var' => 'Service/product name',
    'service_name_alt_var' => 'Alternative service name',
    'service_id_var' => 'Service numeric ID',
    'domain_var' => 'Associated domain',
    'dedicated_ip_var' => 'Server/VPS dedicated IP',
    'username_var' => 'Service access username',
    'password_var' => 'Service access password',
    'activation_date_var' => 'Service activation date',
    'suspension_date_var' => 'Service suspension date',
    'unsuspension_date_var' => 'Service unsuspension date',
    'termination_date_var' => 'Service termination date',
    'suspension_reason_var' => 'Service suspension reason',
    
    // Cancellation Variables
    'cancellation_type_var' => 'Cancellation type (Immediate, End of Period)',
    'request_date_var' => 'Cancellation request date',
    
    // Quote Variables
    'quote_number_var' => 'Quote number',
    'quote_subject_var' => 'Quote subject',
    'quote_value_var' => 'Quote total amount',
    'quote_validity_var' => 'Quote validity date',
    'quote_status_var' => 'Quote status (Draft, Delivered, Accepted, etc)',
    'quote_items_var' => 'Items included in quote',
    'acceptance_date_var' => 'Quote acceptance date',
    'quote_status_draft' => 'Draft',
    'quote_status_delivered' => 'Delivered',
    'quote_status_on_hold' => 'On Hold', 
    'quote_status_accepted' => 'Accepted',
    'quote_status_lost' => 'Lost',
    'quote_status_dead' => 'Cancelled',
    
    // System Variables
    'verification_code_var' => 'WhatsApp verification code',
    'registration_date_var' => 'Client registration date',
    'modification_date_var' => 'Data modification date',
    'new_password_var' => 'New password set by client',
    'changes_var' => 'List of changes made',
    'service_type_var' => 'Service type (Hosting, Reseller, VPS, etc)',
    'product_name_var' => 'Contracted product name',
    
    // Formatting
    'bold' => 'Bold',
    'italic' => 'Italic',
    'strikethrough' => 'Strikethrough',
    'monospace' => 'Monospace',
    'emojis' => 'Emojis',
    'select_text_to_format' => 'Select text you want to format',
    
    // Messages
    'are_you_sure' => 'Are you sure?',
    'confirm_delete_template' => 'Are you sure you want to delete template "%s"?',
    'confirm_reset_validation' => 'Are you sure you want to reset validation for client "%s"?',
    'confirm_remove_gateway' => 'Are you sure you want to remove gateway "%s"?',
    'confirm_delete_log' => 'Are you sure you want to delete this log?',
    'confirm_clear_logs' => 'Are you sure you want to clear all logs? This action cannot be undone.',
    'confirm_send_pending_validations' => 'Send validation codes to all pending clients?',
    'template_created' => 'Template created successfully',
    'template_updated' => 'Template updated successfully',
    'template_activated' => 'Template activated',
    'template_deactivated' => 'Template deactivated',
    'template_deleted' => 'Template removed',
    'code_resent' => 'Code Resent',
    'validation_reset' => '🔃 Validation Reset',
    'gateway_installed' => 'Gateway installed successfully',
    'gateway_removed' => 'Gateway removed successfully',
    'logs_cleared' => 'Logs cleared successfully',
    'logs_cleared_success' => 'All log records have been cleared',
    'settings_saved' => 'Settings saved successfully',
    'cache_cleared' => 'Cache cleared',
    'templates_synced' => 'Templates synchronized',
    
    // Error Messages
    'invalid_id' => 'Invalid ID',
    'template_not_found' => 'Template not found',
    'client_not_found' => 'Client not found',
    'validation_not_found' => 'Validation not found',
    'invalid_gateway' => 'Invalid gateway',
    'log_not_found' => 'Log not found',
    'invalid_data' => 'Invalid data',
    'fill_name_event_content' => 'Fill name, event and content',
    'empty_message' => 'Empty message',
    'invalid_client' => 'Invalid client',
    'client_no_phone' => 'Client has no phone number',
    'unrecognized_action' => 'Unrecognized action',
    'api_credentials_not_configured' => 'API credentials not configured',
    'connection_established' => 'Connection established successfully',
    'connection_error' => 'Error connecting to API',
    
    // Log Types
    'message_sent' => 'Message Sent',
    'message_failed' => 'Send Failed',
    'validation_sent' => '✅ Validation Sent',
    'validation_success' => '⭐ Validation Completed',
    'gateway_sync' => 'Gateway Sync',
    'system_error' => 'System Error',
    'gateway_event' => 'Gateway Event',
    'test_message_event' => 'Test Message',
    'test_message_simulation' => 'Test Message Simulation',
    
    // Development
    'under_development' => 'Under Development',
    'feature_under_development' => 'This feature is still under development.',

    // Hooks - Additional messages
    'access_denied_message' => 'Unauthorized access.', 
    'new_client_log' => 'New Client',
    'password_changed_log' => 'Password changed',
    'confidential' => 'CONFIDENTIAL',
    'invoice_created_log' => 'Invoice created',
    'invoice_paid_log' => 'Invoice Paid',
    'invoice_cancelled_log' => 'Invoice Cancelled',
    'invoice_reminder_log' => 'Invoice reminder',
    'ticket_opened_log' => 'Ticket Opened',
    'ticket_replied_log' => 'Ticket Replied',
    'service_activated_log' => 'Service activated',
    'service_suspended_log' => 'Service Suspended',
    'service_unsuspended_log' => 'Service Unsuspended',
    'service_terminated_log' => 'Service Terminated',
    'cancellation_request_log' => 'Cancellation Request',
    'client_data_updated_log' => 'Client data updated',
    'quote_created_log' => 'Quote Created',
    'quote_updated_log' => 'Quote Updated',
    'quote_accepted_log' => 'Quote Accepted',
    'custom_message_log' => 'Custom message',
    'invoice_created_notification_sent' => 'Invoice created - notification sent',
    'payment_confirmed_notification_sent' => 'Payment confirmed - notification sent',
    'invoice_cancelled_notification_sent' => 'Invoice cancelled - notification sent',
    'quote_created_notification_sent' => 'Quote created - notification sent',
    'quote_accepted_notification_sent' => 'Quote accepted - notification sent',
    'cancellation_request_notified' => 'Cancellation request notified',
    'ticket_opened_notification_sent' => 'Ticket opened - notification sent',
    'ticket_reply_notification_sent' => 'Ticket reply - notification sent',
    'service_activated_notification_sent' => 'Service activated - notification sent',
    'reminder_sent' => 'Reminder sent',
    'password_notification_sent_successfully' => 'Password notification sent successfully',
    'cancellation_type_immediate' => 'Immediate',
    'cancellation_type_end_of_period' => 'End of Period',
    'priority_low' => 'Low',
    'priority_medium' => 'Medium',
    'priority_high' => 'High',
    'priority_critical' => 'Critical',
    'unknown_error' => 'Unknown error',
    'not_specified' => 'Not specified',
    'our_team' => 'Our team',
    'host_default' => 'Host',
    'service' => 'Service',
    'our_provider' => 'Our Provider',
    'provider' => 'Provider',
    'others' => 'Others',
    'hosting_account' => 'Hosting Account',
    'reseller_account' => 'Reseller Account',
    'dedicated_vps_server' => 'Dedicated/VPS Server',
    'hosting' => 'Hosting',
    'reseller' => 'Reseller',
    'other_services' => 'Other Services',
    'day' => 'day',
    'days' => 'days',
    'ago' => 'ago',
    'overdue_for' => 'overdue for',
    'due_in' => 'due in',
    'one_day_ago' => '1 day ago',
    'client_no_validated_whatsapp' => 'Client does not have validated WhatsApp',
    'whatsapp_validation_required_not_configured' => 'WhatsApp validation required but not configured',
    'code_sent_to_whatsapp' => 'Code sent to your WhatsApp!',
    'whatsapp_validated_successfully' => 'WhatsApp validated successfully!',
    'invalid_code_try_again' => 'Invalid code. Please try again.',
    'not_verified' => 'Not Verified',
    'not_registered' => 'Not registered',
    'message_blocked_whatsapp_not_validated' => 'Message blocked - WhatsApp not validated',
    'message_blocked_whatsapp_not_validated_colon' => 'Message blocked: WhatsApp not validated',
    'whatsapp_validated_send_allowed' => 'WhatsApp validated - send allowed',
    'whatsapp_validation_disabled' => 'WhatsApp validation disabled',
    'enter_code_to_validate_whatsapp' => 'Enter this code in the client area to validate your WhatsApp.\n\n',
    'sending' => 'Sending...',
    'send_whatsapp_reminder' => 'Send WhatsApp Reminder',
    'reminder_sent_successfully_to' => 'Reminder sent successfully to',
    'select_quick_reply' => '-- Select a quick reply --',
    'type_message_to' => 'Type your message to',
    'type_your_message_here' => 'Type your message here...',
    'would_like_more_info' => 'I would like more information',
    'would_like_more_info_punctuated' => '! I would like more information.',
    'button_displayed' => 'Button displayed',
    'no_return' => 'No Return',
    'pix_qr_code' => 'PIX QR Code',
    'details_updated' => 'Details updated',
    'info_updated' => 'Information updated',
    'no_service' => 'No service',
    'no_domain' => 'No domain',
    'other_reason' => 'Other reason',
    'no_longer_required' => 'No longer required',
    'going_to_competitor' => 'Going to competitor',
    'too_expensive' => 'Too expensive',
    'technical_issues' => 'Technical issues',
    'userid_not_found_in_vars' => 'UserChangePassword: userid not found in vars',
    'user_client_relation_not_found' => 'User-client relation not found for userid',
    'could_not_find_client_id' => 'Could not find client_id for user ID',
    'template_password_changed_not_found' => 'Template password_changed not found or inactive',
    'client_id_label' => 'Client ID',
    'not_found' => 'not found',
    'client_found' => 'Client found',
    'phone_number_not_found_for_client' => 'Phone number not found for client',
    'preparing_send' => 'Preparing send',
    'error_sending_notification' => 'Error sending notification',
    'detailed_exception' => 'Detailed exception',
    'exception' => 'Exception',
    'client_id_found_via_tblusers' => 'Client_id found via tblusers',
    'client_id_found_via_tblusers_clients' => 'Client_id found via tblusers_clients',
    'template_not_found_or_inactive' => 'Template not found or inactive',
    'module_disabled' => 'Module disabled',
    'service_id_label' => 'Service ID',
    'template_found' => 'Template found',
    'service_not_found' => 'Service not found',
    'client_number_label' => 'Client number',
    'phone_number_not_found' => 'Phone number not found',
    'validation_status_label' => 'Validation status',
    'send_result_label' => 'Send result',
    'exception_caught' => 'Exception caught',
    'no_changes_detected' => 'No changes detected',
    'changes_detected' => 'Changes detected',
    'invoice_not_found' => 'Invoice not found',
    'ticket_not_found' => 'Ticket not found',
    'quote_not_found' => 'Quote not found',
    'variable_defined_as_empty' => 'Variable defined as empty',
    'missing_required_variables' => 'Missing required variables',
    'hook_triggered' => 'Hook triggered',
    'validation_scenarios' => 'Validation scenarios',
    'boleto_found' => 'Boleto found',
    'pix_found' => 'PIX found',
    'invoice_data' => 'Invoice data',
    'iugupix_raw_data' => 'Iugupix raw data',
    'final_extracted_data' => 'Final extracted data',
    'starting' => 'Starting',
    'image_sent' => 'Image sent',
    'text_sent' => 'Text sent',
    'template_not_found_for_service' => 'Template not found for service',
    'email_replaced_by_whatsapp' => 'Email replaced by WhatsApp',
    'client_add_hook_error' => 'ClientAdd Hook: ',
    'user_change_password_hook_error' => 'UserChangePassword Hook ERROR: ',
    'invoice_created_hook_error' => 'InvoiceCreated Hook: ',
    'invoice_paid_hook_error' => 'InvoicePaid Hook: ',
    'invoice_cancelled_hook_error' => 'InvoiceCancelled Hook: ',
    'invoice_payment_reminder_hook_error' => 'InvoicePaymentReminder Hook: ',
    'ticket_open_hook_error' => 'TicketOpen Hook: ',
    'ticket_admin_reply_hook_error' => 'TicketAdminReply Hook: ',
    'after_module_create_hook_error' => 'AfterModuleCreate Hook: ',
    'after_module_suspend_hook_error' => 'AfterModuleSuspend Hook: ',
    'after_module_unsuspend_hook_error' => 'AfterModuleUnsuspend Hook: ',
    'after_module_terminate_hook_error' => 'AfterModuleTerminate Hook: ',
    'cancellation_request_hook_error' => 'CancellationRequest Hook: ',
    'client_edit_hook_error' => 'ClientEdit Hook: ',
    'quote_created_hook_error' => 'QuoteCreated Hook: ',
    'quote_modified_hook_error' => 'QuoteModified Hook: ',
    'quote_accepted_hook_error' => 'QuoteAccepted Hook: ',
    'send_custom_message_hook_error' => 'SendCustomMessage Hook: ',
    'admin_area_client_summary_action_links_hook_error' => 'AdminAreaClientSummaryActionLinks Hook: ',
    'admin_invoices_controls_output_hook_error' => 'AdminInvoicesControlsOutput Hook: ',
    'email_presend_hook_error' => 'EmailPreSend Hook: ',
    'invoice_cancelled_invoice_not_found_prefix' => 'InvoiceCancelled: Invoice not found - ',
    'quote_created_quote_not_found_prefix' => 'QuoteCreated: Quote not found - ',
    'quote_modified_quote_not_found_prefix' => 'QuoteModified: Quote not found - ',
    'quote_accepted_quote_not_found_prefix' => 'QuoteAccepted: Quote not found - ',
    'cancellation_request_service_id_not_provided' => 'CancellationRequest: Service ID not provided',
    'cancellation_request_service_not_found_prefix' => 'CancellationRequest: Service not found - ',
    'error_getting_cancellation_data_prefix' => 'Error getting cancellation data: ',
    'error_preparing_quote_variables_prefix' => 'Error preparing quote variables: ',
    'error_getting_payment_data_prefix' => 'Error getting payment data: ',
    'error_in_whatsapp_validation_prefix' => 'Error in WhatsApp validation: ',
    'error_getting_client_variables_prefix' => 'Error getting client variables: ',
    'send_message_with_media_error_prefix' => 'send_message_with_media: ',
    'error_in_automatic_log_cleanup_prefix' => 'Error in automatic log cleanup: ',
    'validation_code_header' => '⚙️ *WhatsApp Validation Code*\n\n',
    'your_validation_code_is' => 'Your validation code is:',
    'code_expires_24_hours' => 'This code expires in 24 hours.',
    'whatsapp_validation_label' => 'WhatsApp Validation',

    // Auto Login - General
    'autologin_title' => 'Auto Login (use in emails)',
    'autologin_subtitle' => 'Manage direct access tokens for invoices and tickets',

    // Auto Login - Statistics
    'active_tokens' => 'Active Tokens',
    'expired_tokens' => 'Expired Tokens',
    'used_tokens' => 'Used Tokens',
    'used_today' => 'Used Today',
    'active_tokens_desc' => 'valid and usable tokens.',
    'expired_tokens_desc' => 'tokens that have expired.',
    'total_clicks_desc' => 'accesses generated by tokens.',
    'total_tokens_desc' => 'total generated tokens.',

    // Auto Login - Table
    'tokens_history' => 'Tokens History',
    'type' => 'Type',
    'target' => 'Target',
    'token' => 'Token',
    'created_at' => 'Created at',
    'expires_at' => 'Expires at',
    'used_at' => 'Used at',
    'ip_address' => 'IP Address',
    'status' => 'Status',

    // Auto Login - Status
    'active' => 'Active',
    'expired' => 'Expired',
    'used' => 'Used',

    // Auto Login - Types
    'invoice' => 'Invoice',
    'ticket' => 'Ticket',

    // Auto Login - Template Variables
    'link_fatura_autologin' => 'Direct Invoice Access Link',
    'link_ticket_autologin' => 'Direct Ticket Access Link',
    'token_autologin' => 'Access Token',
    'token_expiracao' => 'Token Expiration',

    // MessageProcessor - Error and log messages
    'template_error_prefix' => 'Template Error: ',
    'client_variables_error_prefix' => 'Client Variables Error: ',
    'invoice_variables_error_prefix' => 'Invoice Variables Error: ',
    'ticket_variables_error_prefix' => 'Ticket Variables Error: ',
    'service_variables_error_prefix' => 'Service Variables Error: ',
    'quote_variables_error_prefix' => 'Quote Variables Error: ',
    'message_split_into_parts' => 'Message split into parts',
    'invoice_variables_prepared' => 'Invoice variables prepared',
    'qr_code_part_split' => 'QR Code part split',

    // Admin & Hooks - System messages
    'connection_error_prefix' => 'Connection error: ',
    'export_settings_error' => 'Error exporting settings',
    'token_copied_to_clipboard' => 'The token has been copied to the clipboard.',
    'send_code_error' => 'Error sending code',
    'user_change_password_userid_not_found' => 'UserChangePassword: userid not found in vars: ',
    'suspension' => 'Suspension',
    'reactivation' => 'Reactivation',
    'domain' => 'Domain',
    'address' => 'Address',
    'request_error_prefix' => 'Request error: ',
    'confirm_validation' => 'Confirm Validation',
    'send_validation_code_to_client' => 'Send validation code to client?',
    'validation_code_sent_success_short' => 'Validation code sent!',
    'priority_medium_icon' => '🟡 Medium',
    'not_verified_icon' => '⚠️ Not Verified',
    'service_number_prefix' => 'Service #',

    // New Keys for Logs/Debug
    'system_cleanup_log' => 'System Cleanup',
    'debug_service_suspended' => 'Debug: Service Suspended',
    'debug_service_unsuspended' => 'Debug: Service Unsuspended',
    'debug_service_terminated' => 'Debug: Service Terminated',
    'debug_invoice_created' => 'Debug: Invoice Created',
    'debug_ticket_opened' => 'Debug: Ticket Opened',
    'debug_default_variables' => 'Debug: Default Variables',
    'debug_validation_test' => 'Debug: Validation Test',

    // WhatsApp Validation - Interface
    'whatsapp_validation_subtitle' => 'Validate your number to receive important notifications',
    'phone_number_label' => 'WhatsApp Number',
    'phone_number_help' => 'Number registered in WHMCS. To change it, update your profile.',
    'send_code_button' => 'Send Verification Code',
    'change_phone_button' => 'Change Number',
    'verification_code_label' => 'Verification Code',
    'verification_code_help' => 'Enter the 6-digit code sent to your WhatsApp',
    'code_expires_in_15_minutes' => 'Code expires in 15 minutes',
    'validate_code_button' => 'Validate Code',
    'back_to_change_phone' => 'Back / Correct Number',
    
    // JavaScript Messages
    'sending_code' => 'Sending code...',
    'code_sent_title' => 'Code Sent!',
    'code_sent_text' => 'Check your WhatsApp and enter the 6-digit code.',
    'validating_code' => 'Validating code...',
    'validation_success_title' => 'Validation Completed!',
    'validation_success_text' => 'Your WhatsApp has been successfully validated!',
    'error_title' => 'Error',
    'code_expired_title' => 'Code Expired',
    'code_expired_text' => 'The verification code has expired. Request a new code.',
    'ok_button' => 'OK',
    'try_again' => 'Try Again',
    
    // Confirmations
    'confirm_change_phone' => 'Do you want to correct the number?',
    'confirm_change_phone_text' => 'You will be redirected to update your number in your profile.',
    'yes_change' => 'Yes, correct',
    
    // Backend
    'code_expired' => 'Code expired. Request a new code.',
    'back_resend_button' => 'Back and Resend Code',

    // Gateways
    'gateways_subtitle_new' => 'Select the payment gateway to extract PIX and Boleto data',
    'how_to_create_gateway' => 'How to create a gateway?',
    'no_gateways_found' => 'No gateways found',
    'no_gateways_description' => 'No gateway was found in the gateways/ folder. Create your first gateway following the tutorial.',
    'learn_how_to_create' => 'Learn how to create',
    'active_gateway' => 'Active Gateway',
    'none_selected' => 'None selected',
    'none_disabled' => 'None (disabled)',
    'no_gateway_description' => 'Do not extract PIX/Boleto data',
    'select_this_gateway' => 'Select this gateway',
    'file' => 'File',
    'version' => 'Version',
    'gateway_information' => 'Gateway Information',
    'how_it_works' => 'How It Works',
    'available_variables' => 'Available Variables',
    'var_codigopix' => 'PIX code for payment',
    'var_qr_code_url' => 'PIX QR Code image URL',
    'var_linhadigitavel' => 'Boleto digitable line',
    'var_link_fatura' => 'Invoice view link (PDF or HTML)',
    'view_all_variables' => 'View all variables',
    'confirm_change_gateway' => 'Confirm gateway change?',
    'confirm_change_gateway_text' => 'Are you sure you want to change the active gateway? This will affect PIX/Boleto data extraction.',
    'yes_change' => 'Yes, change',
    'cancel' => 'Cancel',
    'success' => 'Success',
    'error' => 'Error',
    'unknown_error' => 'Unknown error',
    'connection_error' => 'Server connection error',
    'invalid_gateway' => 'Invalid gateway',
    'gateway_file_not_found' => 'Gateway file not found',
    'gateway_deactivated_success' => 'Gateway deactivated successfully',
    'gateway_activated_success' => 'Gateway activated successfully:',
    'error_saving_gateway' => 'Error saving gateway',
    'file_none' => 'No files.',

    // Tutorial Modal
    'tutorial_title' => 'How to Create Your Own Gateway',
    'close' => 'Close',
    'tutorial_full_docs' => 'Full Documentation',

    // Step 1
    'tutorial_step1_title' => 'Step 1: Create the File',
    'tutorial_step1_desc' => 'Create a file in the <code>/modules/addons/zapcel/gateways/</code> folder with your gateway name:',
    'tutorial_step1_ex1' => 'Mercado Pago → <code>MercadoPagoGateway.php</code>',
    'tutorial_step1_ex2' => 'Banco Inter → <code>BancoInterGateway.php</code>',
    'tutorial_step1_ex3' => 'PagHiper → <code>PagHiperGateway.php</code>',

    // Step 2
    'tutorial_step2_title' => 'Step 2: Basic Structure',
    'tutorial_step2_desc' => 'Paste this code into the created file:',
    'tutorial_code_classname' => 'YourGatewayGateway',
    'tutorial_code_gatewayname' => 'yourgateway',
    'tutorial_code_comment_pix' => 'Fetch PIX data from database',
    'tutorial_code_comment_boleto' => 'Fetch Boleto data from database',
    'tutorial_code_table_pix' => 'your_pix_table',
    'tutorial_code_table_boleto' => 'your_boleto_table',

    // Step 3
    'tutorial_step3_title' => 'Step 3: Discover Tables and Fields',
    'tutorial_step3_desc' => 'Use phpMyAdmin or MySQL to find where your gateway stores data:',
    'tutorial_sql_comment1' => 'List gateway tables',
    'tutorial_sql_comment2' => 'View table structure',
    'tutorial_sql_comment3' => 'View sample data',

    // Step 4
    'tutorial_step4_title' => 'Step 4: Activate the Gateway',
    'tutorial_step4_desc' => 'After saving the file:',
    'tutorial_step4_item1' => 'Reload this page',
    'tutorial_step4_item2' => 'Your gateway will appear automatically in the list',
    'tutorial_step4_item3' => 'Select it and click "Save"',
    'tutorial_step4_item4' => 'Done! The system will start using your gateway',

    // Tips
    'tutorial_tips_title' => 'Important Tips',
    'tutorial_tip1' => 'Use <code>try-catch</code> to avoid errors',
    'tutorial_tip2' => 'Always return <code>null</code> if there is no data',
    'tutorial_tip3' => 'Test with a real invoice before using in production',
    'tutorial_tip4' => 'Document your code to facilitate maintenance',
    
        // Marketing Campaigns
    'campaigns_title' => 'Marketing Campaigns',
    'campaigns_subtitle' => 'Manage WhatsApp campaigns for WHMCS clients',
    'active_campaigns' => 'Active Campaigns',
    'paused_campaigns' => 'Paused Campaigns',
    'sent_today' => 'Sent Today',
    'total_campaigns' => 'Total Campaigns',
    'campaigns_list' => 'Campaigns List',
    'new_campaign' => 'New Campaign',
    'no_campaigns_found' => 'No campaigns found.',
    'create_first_campaign' => 'Create first campaign',
    'campaign_name' => 'Campaign Name',
    'sent' => 'Sent',
    'failed' => 'Failed',
    'progress' => 'Progress',
    'contacts' => 'contacts',
    'reset' => 'Reset',
    'activity' => 'Activity',
    'campaign_form_title' => 'Campaign Form',
    'language' => 'Language',
    'target_products' => 'Target Products/Services',
    'service_status' => 'Service Status',
    'client_status' => 'Client Status',
    'message_help' => 'Use the variables and formatting above to customize the message.',
    'schedule_start' => 'Start Date/Time',
    'schedule_help' => 'Leave blank to start immediately when activated.',
    'send_mode' => 'Send Mode',
    'all_day' => 'All Day (24h)',
    'business_hours' => 'Business Hours (07:00 to 18:00)',
    'delay_min' => 'Minimum Delay (seconds)',
    'delay_max' => 'Maximum Delay (seconds)',
    'delay_info' => 'The mandatory minimum and maximum delays are 7 and 13 seconds. The system randomly selects a value between them for each send.',
    'confirm_reset' => 'Confirm Reset',
    'confirm_reset_text' => 'This will reset the counters and re-queue the campaign. Continue?',
    'yes_reset' => 'Yes, reset',
    'confirm_delete' => 'Confirm Deletion',
    'confirm_delete_text' => 'This will delete the campaign and all related records. Continue?',
    'yes_delete' => 'Yes, delete',
    'campaign_saved' => 'Campaign saved successfully!',
    'campaign_reset' => 'Campaign reset successfully!',
    'campaign_deleted' => 'Campaign deleted successfully!',
    'status_draft' => 'Draft',
    'status_active' => 'Active',
    'status_paused' => 'Paused',
    'status_finished' => 'Finished',
    'status_scheduled' => 'Scheduled',
    'active_campaigns_desc' => 'Campaigns in execution.',
    'paused_campaigns_desc' => 'Temporarily paused campaigns.',
    'sent_today_desc' => 'Messages sent today.',
    'total_campaigns_desc' => 'All campaigns created.',
    'client_variables' => 'Client',
    'service_variables' => 'Service',
    'campaign_start' => 'Campaign Started',
    'campaign_end'   => 'Campaign Finished',

];