<?php
/**
 * Zapcel WHMCS - Arquivo de Idioma Português Brasileiro
 *
 * @package    Zapcel
 * @author     Hostcel
 * @version    2.0.0
 */
return [
    // Geral
    'module_name' => 'Zapcel WHMCS',
    'module_description' => 'Sistema de notificações via WhatsApp',
    'welcome' => 'Bem-vindo ao Zapcel',
    'save' => 'Salvar',
    'cancel' => 'Cancelar', 
    'back' => 'Voltar',
    'edit' => 'Editar',
    'delete' => 'Excluir',
    'activate' => 'Ativar',
    'deactivate' => 'Desativar',
    'active' => 'Ativo',
    'inactive' => 'Inativo',
    'status' => 'Status',
    'actions' => 'Ações',
    'search' => 'Buscar',
    'filter' => 'Filtrar',
    'refresh' => 'Atualizar',
    'clear' => 'Limpar',
    'export' => 'Exportar',
    'import' => 'Importar',
    'download' => 'Download',
    'upload' => 'Upload',
    'confirm' => 'Confirmar',
    'success' => 'Sucesso',
    'error' => 'Erro',
    'warning' => 'Aviso',
    'info' => 'Informação',
    'loading' => 'Carregando',
    'response_log' => 'Resposta',
    
    // Dashboard
    'dashboard' => 'Dashboard',
    'dashboard_title' => 'Zapcel WHMCS - Dashboard',
    'dashboard_subtitle' => 'Painel de controle do sistema de notificações WhatsApp',
    'total_messages' => 'Total de Mensagens',
    'success_rate' => 'Taxa de Sucesso',
    'successful_messages' => 'Mensagens com Sucesso',
    'failed_messages' => 'Mensagens com Falha',
    'templates' => 'Templates',
    'active_templates' => 'ativos',
    'whatsapp_validated' => 'WhatsApp Validado',
    'clients_with_whatsapp_verified' => 'Clientes com WhatsApp verificado',
    'today' => 'Hoje',
    'recent_messages' => 'Últimas Mensagens',
    'client' => 'Cliente',
    'event' => 'Evento',
    'date' => 'Data',
    'all' => 'Todos',
    'events' => 'Eventos',
    'no_messages_sent' => 'Nenhuma mensagem enviada ainda',
    'system_status' => 'Status do Sistema',
    'database' => 'Banco de Dados',
    'whatsapp_api' => 'API WhatsApp',
    'active_hooks' => 'Hooks Ativos',
    'connected' => 'Conectado',
    'disconnected' => 'Desconectado',
    'quick_actions' => 'Ações Rápidas',
    'manage_templates' => 'Templates',
    'manage_gateways' => 'Gateways',
    'validations' => 'Validações',
    'view_logs' => 'Logs',
    'test_message' => 'Testar Mensagem',
    'settings' => 'Configurações',
    'debug_logging' => 'Debug Logging',
    'debug_logging_tooltip' => 'Logs detalhados das ações do sistema. Recomendado apenas para troubleshooting.',
    'debug_enabled_tooltip' => 'Logs detalhados ativos',
    'debug_disabled_tooltip' => 'Apenas logs essenciais',
    'enabled' => 'Habilitado',
    'disabled' => 'Desabilitado',
    'system' => 'Sistema',
    'developer' => 'Por',
    'quick_reply_badge' => 'Resposta Rápida',
    
    // Templates
    'manage_message_templates' => 'Gerenciar Templates de Mensagem',
    'templates_subtitle' => 'Configure as mensagens automáticas enviadas pelo WhatsApp',
    'template_name' => 'Nome do Template',
    'trigger_event' => 'Evento de Disparo',
    'usage' => 'Uso',
    'last_update' => 'Última Atualização',
    'new_template' => 'Novo Template',
    'no_templates_found' => 'Nenhum template encontrado',
    'create_first_template' => 'Criar Primeiro Template',
    'create_template' => 'Criar Template',
    'select_event' => 'Selecione um evento...',
    'invoice_created' => 'Fatura Criada',
    'invoice_reminder' => 'Lembrete de Fatura',
    'invoice_paid' => 'Fatura Paga',
    'ticket_created' => 'Ticket Criado',
    'ticket_replied' => 'Ticket Respondido',
    'service_activated' => 'Serviço Ativado',
    'service_suspended' => 'Serviço Suspenso',
    'service_unsuspended' => 'Serviço Reativado',
    'service_terminated' => 'Serviço Cancelado',
    'client_added' => 'Cliente Adicionado',
    'invoice_cancelled' => 'Fatura Cancelada',
    'invoice_reminder_1' => '1º Lembrete de Fatura',
    'invoice_reminder_2' => '2º Lembrete de Fatura',
    'invoice_reminder_3' => '3º Lembrete de Fatura',
    'ticket_opened' => 'Ticket Aberto',
    'ticket_reply' => 'Resposta no Ticket',
    'cancellation_request' => 'Solicitação de Cancelamento',
    'client_edited' => 'Cliente Editado',
    'password_changed' => 'Senha Alterada',
    'quote_created' => 'Cotação Criada',
    'quote_modified' => 'Cotação Modificada',
    'quote_accepted' => 'Cotação Aceita',
    'email_presend' => 'Substituição de Email',
    'email_replaced' => 'Email Substituído',
    'whatsapp_validation' => 'Validação WhatsApp',
    'message_template' => 'Template da Mensagem',
    'enter_message_template' => 'Digite o template da mensagem...',
    'use_variables_in_braces' => 'Use variáveis entre chaves {exemplo}. Selecione o texto e clique nos botões para formatar.',
    'available_variables' => 'Variáveis disponíveis',
    'general_variables' => 'Gerais',
    'invoice_variables' => 'Faturas',
    'ticket_variables' => 'Tickets',
    'edit_template' => 'Editar Template',
    'edit_template_subtitle' => 'Modifique o template de mensagem WhatsApp',
    'event_cannot_be_changed' => 'O evento não pode ser alterado após a criação',
    'template_statistics' => 'Estatísticas',
    'created_at' => 'Criado em',
    'updated_at' => 'Atualizado em',
    'cpf_cnpj_var' => 'CPF do cliente',
    
    // Statistics
    'detailed_statistics' => 'Estatísticas Detalhadas',
    'statistics_subtitle' => 'Relatórios completos e análises do sistema',
    'period' => 'Período',
    'day' => 'Hoje',
    'week' => 'Esta Semana',
    'month' => 'Este Mês',
    'year' => 'Este Ano',
    'statistics_by_event_type' => 'Estatísticas por Tipo de Evento',
    'total' => 'Total',
    'rate' => 'Taxa',
    
    // Validation
    'whatsapp_validation_title' => 'Validação WhatsApp',
    'validation_subtitle' => 'Gerencie a validação de números WhatsApp dos clientes',
    'total_clients' => 'Total Clientes',
    'validated' => 'Validados',
    'pending' => 'Pendentes',
    'blocked' => 'Bloqueados',
    'invalidated' => 'Invalidados',
    'validation_history' => 'Filtrar Validações',
    'phone' => 'Telefone',
    'code' => 'Código',
    'attempts' => 'Tentativas',
    'last_attempt' => 'Última Tentativa',
    'send_pending' => 'Enviar Pendentes',
    'resend_code' => 'Reenviar Código',
    'view_details' => 'Ver Detalhes',
    'reset_validation' => 'Resetar Validação',
    'validation_details' => 'Detalhes da Validação',
    'not_started' => 'Não Iniciado',
    'search_client' => 'Digite sua pesquisa...',
    'close' => 'Fechar',
    'validation_code_resent_success' => 'Código de validação reenviado com sucesso!',
    'send_code_failed' => 'Falha ao enviar código de verificação',
    'log_validation_code_sent' => 'Código de verificação enviado',
    'validation_code_sent_success' => 'Código de verificação enviado com sucesso',
    'log_send_code_failed_prefix' => 'Falha no envio do código:',
    'validation_not_found' => 'Nenhuma validação pendente encontrada',
    'validation_already_processed' => 'Validação já foi processada',
    'code_expired_request_new' => 'Código expirado. Solicite um novo código.',
    'too_many_attempts_blocked' => 'Número bloqueado devido a muitas tentativas falhas',
    'invalid_code_attempts_left' => 'Código inválido. {attempts} tentativas restantes.',
    'log_whatsapp_validated' => 'WhatsApp validado com sucesso',
    'whatsapp_validated_success' => 'WhatsApp validado com sucesso!',
    'log_validation_failed_prefix' => 'Falha na verificação:',
    'validation_not_started' => 'Validação não iniciada',
    'validation_none_found' => 'Nenhuma validação encontrada',
    'resend_code_failed' => 'Falha ao reenviar código',
    'log_code_resent' => 'Código reenviado',
    'code_resent_success' => 'Código reenviado com sucesso',
    'log_resend_failed_prefix' => 'Falha no reenvio:',
    'log_phone_updated_whmcs' => 'Telefone atualizado no WHMCS',
    'log_phone_update_error' => 'Erro ao atualizar telefone',
    'phone_update_error' => '❌ Erro Atualização Telefone',
    'validation_template_default' => "▫️ *Validação WhatsApp* ▫️

Olá! ➡️ 

Para confirmar seu número WhatsApp e receber nossas notificações, use o código abaixo:

⚡ *Código de Verificação:* `{codigo_validacao}`

Este código expira em 15 minutos.

⚠️ *Não compartilhe este código com ninguém.*

Atenciosamente,
*{provedor}*",
    'provider_default_name' => 'Nosso Provedor',
    'log_validation_reset' => 'Validação resetada',
    'validation_reset_success' => 'Validação resetada com sucesso', 
    'validation_resent' => '✔️ Validação Reenviada',
    'total_clients_desc' => 'Clientes com tentativa de validação.',
    'validated_desc' => 'WhatsApp confirmado com sucesso.',
    'pending_desc' => 'aguardando confirmação do código.',
    'invalidated_desc' => 'expirados, inválidos ou bloqueados.',
    'validation_failed' => '❌ Validação Falhou',
    'phone_updated' => '☎️ Telefone Atualizado',
    'validation_completed' => '✅ Validação Concluída',
    'validation_sent' => '✅ Validação Enviada',
    'validation_code_sent' => '✅ Código Enviado',
    
    // Gateways
    'payment_gateways' => 'Gateways de Pagamento',
    'gateways_subtitle' => 'Configure os gateways para extração de PIX e boletos',
    'installed' => 'Instalado',
    'not_installed' => 'Não Instalado',
    'last_sync' => 'Última Sincronização',
    'never' => 'Nunca',
    'configure' => 'Configurar',
    'remove' => 'Remover',
    'install_gateway' => 'Instalar Gateway',
    'supported_features' => 'Funcionalidades Suportadas',
    'how_it_works' => 'Como Funciona',
    'automatic_pix_extraction' => 'Extração automática de código PIX (copia e cola)',
    'qrcode_generation' => 'Geração de QR Code PIX',
    'barcode_extraction' => 'Extração de linha digitável do boleto',
    'pdf_download' => 'Download de PDF do boleto',
    'automatic_status_sync' => 'Sincronização automática de status',
    'gateways_integration_info' => 'Os gateways se integram automaticamente com as faturas do WHMCS e extraem as informações de pagamento para envio via WhatsApp.',
    'tip_activate_used_gateways' => 'Dica: Ative apenas os gateways que você utiliza no seu WHMCS.',
    
    // Logs
    'system_logs' => 'Logs do Sistema',
    'logs_subtitle' => 'Registro completo de todas as atividades do sistema',
    'clear_logs' => 'Limpar Logs',
    'date_time' => 'Data/Hora',
    'event_type' => 'Tipo',
    'message' => 'Mensagem',
    'details' => 'Detalhes',
    'all_types' => 'Todos os Tipos',
    'date_from' => 'De',
    'date_to' => 'Até',
    'view_more' => 'ver mais',
    'log_details' => 'Detalhes do Log',
    'showing_records' => 'Exibindo %s de %s registros',
    'filters' => 'Filtros',
    
    // Settings
    'zapcel_settings' => 'Configurações do Zapcel',
    'settings_subtitle' => 'Configure as principais opções do módulo',
    'save_settings' => 'Salvar Configurações',
    'main_settings' => 'Configurações Principais',
    'module_status' => 'Status do Módulo',
    'activate_deactivate_module' => 'Ative ou desative completamente o módulo Zapcel',
    'instance_id' => 'ID da Instância',
    'enter_instance_id' => 'Digite o ID da instância do Zapcel',
    'instance_id_help' => 'ID da instância do Zapcel',
    'access_token' => 'Token de Acesso',
    'enter_access_token' => 'Digite o token de acesso da API Zapcel',
    'access_token_help' => 'Token de acesso da API Zapcel',
    'message_delay' => 'Delay entre Mensagens (segundos)',
    'message_delay_help' => 'Tempo de espera entre o envio de mensagens para evitar bloqueios',
    'max_attempts' => 'Máximo de Tentativas',
    'max_attempts_help' => 'Número máximo de tentativas para envio de uma mensagem',
    'validation_template' => 'Template de Validação',
    'select_template' => 'Selecione um template...',
    'module_language' => 'Idioma do Módulo',
    'portuguese_brazil' => 'Português (Brasil)',
    'english' => 'English',
    'enable_logging' => 'Ativar logging detalhado',
    'enable_logging_help' => 'Recomendado para debug e monitoramento do sistema',
    'log_retention_days' => 'Dias para Manter Logs',
    'log_retention_days_help' => 'Logs mais antigos serão automaticamente excluídos',
    'connection_status' => 'Status da Conexão',
    'test_connection' => 'Testar Conexão',
    'account_info' => 'Informações da Conta',
    'phone_number' => 'Número',
    'instance_name' => 'Instância',
    'battery' => 'Bateria',
    'platform' => 'Plataforma',
    'connect_to_api' => 'Conecte-se à API para ver as informações da conta',
    'quick_actions_settings' => 'Ações Rápidas',
    'clear_cache' => 'Limpar Cache',
    'sync_templates' => 'Sincronizar Templates',
    'export_settings' => 'Exportar Configurações',
    'confirm_clear_cache' => 'Confirmar limpeza de cache',
    'clear_cache_warning' => 'Isso irá esvaziar o cache de templates. As estatísticas e logs NÃO serão afetados.',
    'cache_templates_cleared' => 'Cache de templates esvaziado com sucesso!',
    'clear_cache_templates' => 'Esvaziar Cache de Templates',
    'cache_cleared_success' => 'Cache limpo com sucesso!',
    'cache_clear_error' => 'Erro ao limpar cache',
    'cache_management' => 'Gerenciamento de Cache',
    'settings_imported_by_admin' => 'Configurações importadas pelo administrador',
    'settings_exported_by_admin' => 'Configurações exportadas pelo administrador',
    'cache_cleared_by_admin' => 'Cache limpo pelo administrador',
    'test_message_sent_by_admin' => 'Mensagem de teste enviada pelo administrador',
    'import_settings' => 'Importar Configurações',
    'import_success' => 'Configurações importadas com sucesso!',
    'invalid_file_format' => 'Formato de arquivo inválido. Use apenas arquivos JSON.',
    'select_file_to_import' => 'Selecione o arquivo para importar',
    'import_settings_warning' => 'Isso substituirá as configurações atuais. Tem certeza?',
    'enable_floating_button' => 'Ativar Botão Flutuante WhatsApp',
    'enable_floating_button_help' => 'Exibe um botão flutuante do WhatsApp na área do cliente',
    'company_phone_number' => 'Telefone da Empresa (WhatsApp)', 
    'company_phone_number_help' => 'Número no formato internacional (ex: +55 11 99999-9999 para o Brasil). Se vazio, desativa o botão.',
    'hide_mobile_button' => 'Ocultar Botão em Dispositivos Móveis',
    'hide_mobile_button_help' => 'Esconde o botão flutuante em smartphones e tablets',
    'enable_validation_system' => 'Validação WhatsApp Obrigatória', 
    'enable_validation_system_help' => 'Cliente deve validar WhatsApp para acessar área do cliente',
    'require_validation' => 'Enviar mensagens apenas para números validados',
    'require_validation_help' => 'Se marcado, só enviará mensagens para clientes com WhatsApp validado',
    "autologin_domain" => "Encurtador de Link",
    "autologin_domain_help" => "Alias de domínio opcional (ex: https://hcel.ink/central/) para criar uma URL de autologin encurtada.",

    // Test Message
    'test_whatsapp_message' => 'Testar Mensagem WhatsApp',
    'test_message_subtitle' => 'Envie mensagens de teste para verificar a configuração',
    'configure_test_message' => 'Configurar Mensagem de Teste',
    'destination_client' => 'Cliente Destino',
    'select_client' => 'Selecione um cliente...',
    'test_message_content' => 'Mensagem de Teste',
    'enter_test_message' => 'Digite sua mensagem de teste aqui... Você pode usar as variáveis: {cliente} e {provedor}',
    'available_variables_test' => 'Variáveis disponíveis: {cliente} (nome do cliente) e {provedor} (nome da empresa)',
    'simulate_only' => 'Apenas simular envio (não enviar realmente)',
    'simulate_only_help' => 'Desmarque esta opção para enviar a mensagem real via WhatsApp',
    'send_test_message' => 'Enviar Mensagem de Teste',
    'message_preview' => 'Preview da Mensagem',
    'select_template_or_type' => 'Selecione um template ou digite uma mensagem para ver o preview',
    'available_variables_list' => 'Variáveis Disponíveis',
    'use_variables_below' => 'Use as variáveis abaixo em sua mensagem. Elas serão substituídas automaticamente pelos dados reais do cliente selecionado.',
    'client_full_name' => 'Nome completo do cliente',
    'company_name' => 'Nome da sua empresa',
    'test_variables_tip' => 'Dica: Para testar mensagens com variáveis de faturas ou tickets, use os templates configurados na página de Templates.',
    'test_result' => 'Resultado do Teste',
    'message_preview_title' => 'Prévia da Mensagem',
    'recipient' => 'Destinatário',
    'simulation_mode' => 'Modo simulação: Mensagem não foi enviada (apenas prévia)',
    'message_sent_successfully' => 'Mensagem enviada com sucesso!',
    
    // Variables - Descrições sem redundância
    'variables' => 'Variáveis',
    'general' => 'Gerais',
    'invoices' => 'Faturas',
    'tickets' => 'Tickets',
    'clients' => 'Clientes',
    'services' => 'Serviços',
    'cancellations' => 'Cancelamentos',
    'quotes' => 'Cotações',
    
    // Variáveis Gerais
    'client_var' => 'Nome completo do cliente',
    'provider_var' => 'Nome do provedor/empresa',
    'break_message_var' => 'Envia a mensagem em partes',
    'signature_var' => 'Assinatura configurada nas mensagens',
    'whmcs_url_var' => 'URL completa do sistema WHMCS',
    'current_date_var' => 'Data atual no formato dd/mm/aaaa',
    'current_time_var' => 'Hora atual no formato HH:MM',
    'current_datetime_var' => 'Data e hora completa atual',
    
    // Variáveis de Clientes
    'client_id_var' => 'ID numérico do cliente no sistema',
    'client_firstname_var' => 'Primeiro nome do cliente',
    'client_lastname_var' => 'Sobrenome do cliente',
    'client_email_var' => 'Endereço de e-mail do cliente',
    'client_phone_var' => 'Número de telefone do cliente',
    'client_address_var' => 'Endereço completo do cliente',
    'client_neighborhood_var' => 'Bairro do cliente',
    'client_city_var' => 'Cidade do cliente',
    'client_state_var' => 'Estado do cliente',
    'client_zipcode_var' => 'CEP do cliente',
    'client_country_var' => 'País do cliente',
    
    // Variáveis de Faturas
    'invoice_number_var' => 'Número da fatura',
    'title_var' => 'Título da fatura',
    'value_var' => 'Valor total',
    'due_date_var' => 'Data de vencimento',
    'days_until_due_var' => 'Dias até o vencimento (ex: "hoje", "amanhã", "5 dias")',
    'creation_date_var' => 'Data de criação da fatura',
    'payment_date_var' => 'Data do pagamento da fatura',
    'cancellation_date_var' => 'Data de cancelamento da fatura',
    'pix_code_var' => 'Código PIX para pagamento',
    'qr_code_url_var' => 'URL da imagem do QR Code PIX',
    'barcode_var' => 'Linha digitável do boleto',
    'invoice_link_var' => 'Link para visualizar a fatura',
    'invoice_items_var' => 'Lista de itens da fatura',
    'payment_method_var' => 'Método de pagamento utilizado',
    'cancellation_reason_var' => 'Motivo do cancelamento da fatura',
    
    // Variáveis de Tickets
    'ticket_number_var' => 'Número do ticket',
    'subject_var' => 'Assunto do ticket',
    'ticket_message_var' => 'Mensagem do ticket',
    'department_var' => 'Departamento do ticket',
    'priority_var' => 'Prioridade do ticket (Baixa, Média, Alta, Crítica)',
    'admin_name_var' => 'Nome do atendente que respondeu',
    'ticket_link_var' => 'Link para visualizar o ticket',
    
    // Variáveis de Serviços
    'service_name_var' => 'Nome do serviço/produto',
    'service_name_alt_var' => 'Nome alternativo do serviço',
    'service_id_var' => 'ID numérico do serviço',
    'domain_var' => 'Domínio associado ao serviço',
    'dedicated_ip_var' => 'IP dedicado do servidor/VPS',
    'username_var' => 'Usuário de acesso ao serviço',
    'password_var' => 'Senha de acesso ao serviço',
    'activation_date_var' => 'Data de ativação do serviço',
    'suspension_date_var' => 'Data de suspensão do serviço',
    'unsuspension_date_var' => 'Data de reativação do serviço',
    'termination_date_var' => 'Data de cancelamento do serviço',
    'suspension_reason_var' => 'Motivo da suspensão do serviço',
    
    // Variáveis de Cancelamentos
    'cancellation_type_var' => 'Tipo de cancelamento (Imediato, Fim do Período)',
    'request_date_var' => 'Data da solicitação de cancelamento',
    
    // Variáveis de Cotações
    'quote_number_var' => 'Número da cotação',
    'quote_subject_var' => 'Assunto da cotação',
    'quote_value_var' => 'Valor total da cotação',
    'quote_validity_var' => 'Data de validade da cotação',
    'quote_status_var' => 'Status da cotação (Rascunho, Entregue, Aceita, etc)',
    'quote_items_var' => 'Itens incluídos na cotação',
    'acceptance_date_var' => 'Data de aceitação da cotação',
    'quote_status_draft' => 'Rascunho',
    'quote_status_delivered' => 'Entregue', 
    'quote_status_on_hold' => 'Em Espera',
    'quote_status_accepted' => 'Aceita',
    'quote_status_lost' => 'Perdida',
    'quote_status_dead' => 'Cancelada',
    
    // Variáveis de Sistema
    'verification_code_var' => 'Código de verificação do WhatsApp',
    'registration_date_var' => 'Data de cadastro do cliente',
    'modification_date_var' => 'Data de modificação dos dados',
    'new_password_var' => 'Nova senha definida pelo cliente',
    'changes_var' => 'Lista de alterações realizadas',
    'service_type_var' => 'Tipo de serviço (Hospedagem, Revenda, VPS, etc)',
    'product_name_var' => 'Nome do produto contratado',
    
    // Formatting
    'bold' => 'Negrito',
    'italic' => 'Itálico',
    'strikethrough' => 'Riscado',
    'monospace' => 'Monoespaçado',
    'emojis' => 'Emojis',
    'select_text_to_format' => 'Selecione o texto que deseja formatar',
    
    // Messages
    'are_you_sure' => 'Tem certeza?',
    'confirm_delete_template' => 'Tem certeza que deseja excluir o template "%s"?',
    'confirm_reset_validation' => 'Tem certeza que deseja resetar a validação do cliente "%s"?',
    'confirm_remove_gateway' => 'Tem certeza que deseja remover o gateway "%s"?',
    'confirm_delete_log' => 'Tem certeza que deseja excluir este log?',
    'confirm_clear_logs' => 'Tem certeza que deseja limpar todos os logs? Esta ação não pode ser desfeita.',
    'confirm_send_pending_validations' => 'Deseja enviar códigos de validação para todos os clientes pendentes?',
    'template_created' => 'Template criado com sucesso',
    'template_updated' => 'Template atualizado com sucesso',
    'template_activated' => 'Template ativado',
    'template_deactivated' => 'Template desativado',
    'template_deleted' => 'Template removido',
    'code_resent' => 'Código Reenviado',
    'validation_reset' => '🔃 Validação Resetada',
    'gateway_installed' => 'Gateway instalado com sucesso',
    'gateway_removed' => 'Gateway removido com sucesso',
    'logs_cleared' => 'Logs limpos com sucesso',
    'logs_cleared_success' => 'Todos os registros de logs foram apagados',
    'settings_saved' => 'Configurações salvas com sucesso',
    'cache_cleared' => 'Cache limpo',
    'templates_synced' => 'Templates sincronizados',
    
    // Error Messages
    'invalid_id' => 'ID inválido',
    'template_not_found' => 'Template não encontrado',
    'client_not_found' => 'Cliente não encontrado',
    'validation_not_found' => 'Validação não encontrada',
    'invalid_gateway' => 'Gateway inválido',
    'log_not_found' => 'Log não encontrado',
    'invalid_data' => 'Dados inválidos',
    'fill_name_event_content' => 'Preencha nome, evento e conteúdo',
    'empty_message' => 'Mensagem vazia',
    'invalid_client' => 'Cliente inválido',
    'client_no_phone' => 'Cliente não possui número de telefone',
    'unrecognized_action' => 'Ação não reconhecida',
    'api_credentials_not_configured' => 'Credenciais API não configuradas',
    'connection_established' => 'Conexão estabelecida com sucesso',
    'connection_error' => 'Erro ao conectar com a API',
    
    // Log Types
    'message_sent' => 'Mensagem Enviada',
    'message_failed' => 'Falha no Envio',
    'validation_sent' => '✅ Validação Enviada',
    'validation_success' => '✅ Validação Concluída',
    'gateway_sync' => 'Sincronização Gateway',
    'system_error' => 'Erro do Sistema',
    'gateway_event' => 'Evento de Gateway',
    'test_message_event' => 'Mensagem de Teste',
    'test_message_simulation' => 'Simulação de Mensagem de Teste',
    
    // Development
    'under_development' => 'Em Desenvolvimento',
    'feature_under_development' => 'Esta funcionalidade ainda está em desenvolvimento.',

    // Hooks - Mensagens adicionais
    'access_denied_message' => 'Acesso não autorizado.',
    'new_client_log' => 'Novo Cliente',
    'password_changed_log' => 'Senha alterada',
    'confidential' => 'CONFIDENCIAL',
    'invoice_created_log' => 'Fatura criada',
    'invoice_paid_log' => 'Fatura Paga',
    'invoice_cancelled_log' => 'Fatura Cancelada',
    'invoice_reminder_log' => 'Lembrete de fatura',
    'ticket_opened_log' => 'Ticket Aberto',
    'ticket_replied_log' => 'Ticket Respondido',
    'service_activated_log' => 'Serviço ativado',
    'service_suspended_log' => 'Serviço Suspenso',
    'service_unsuspended_log' => 'Serviço Reativado',
    'service_terminated_log' => 'Serviço Encerrado',
    'cancellation_request_log' => 'Solicitação de Cancelamento',
    'client_data_updated_log' => 'Dados do cliente atualizados',
    'quote_created_log' => 'Cotação Criada',
    'quote_updated_log' => 'Cotação Atualizada',
    'quote_accepted_log' => 'Cotação Aceita',
    'custom_message_log' => 'Mensagem personalizada',
    'invoice_created_notification_sent' => 'Fatura criada - notificação enviada',
    'payment_confirmed_notification_sent' => 'Pagamento confirmado - notificação enviada',
    'invoice_cancelled_notification_sent' => 'Fatura cancelada - notificação enviada',
    'quote_created_notification_sent' => 'Cotação criada - notificação enviada',
    'quote_accepted_notification_sent' => 'Cotação aceita - notificação enviada',
    'cancellation_request_notified' => 'Solicitação de cancelamento notificada',
    'ticket_opened_notification_sent' => 'Ticket aberto - notificação enviada',
    'ticket_reply_notification_sent' => 'Resposta no ticket - notificação enviada',
    'service_activated_notification_sent' => 'Serviço ativado - notificação enviada',
    'reminder_sent' => 'Lembrete enviado',
    'password_notification_sent_successfully' => 'Notificação de senha enviada com sucesso',
    'cancellation_type_immediate' => 'Imediato',
    'cancellation_type_end_of_period' => 'Fim do Período',
    'priority_low' => 'Baixa',
    'priority_medium' => 'Média',
    'priority_high' => 'Alta',
    'priority_critical' => 'Crítica',
    'unknown_error' => 'Erro desconhecido',
    'not_specified' => 'Não especificado',
    'general_category' => 'Geral',
    'our_team' => 'Nossa equipe',
    'host_default' => 'Host',
    'service' => 'Serviço',
    'our_provider' => 'Nosso Provedor',
    'provider' => 'Provedor',
    'others' => 'Outros',
    'hosting_account' => 'Conta de Hospedagem',
    'reseller_account' => 'Conta de Revenda',
    'dedicated_vps_server' => 'Servidor Dedicado/VPS',
    'hosting' => 'Hospedagem',
    'reseller' => 'Revenda',
    'other_services' => 'Outros Serviços',
    'ago' => 'atrás',
    'day' => 'dia',
    'days' => 'dias',
    'overdue_for' => 'está vencida há',
    'due_in' => 'vence em',
    'one_day_ago' => '1 dia atrás', 
    'client_no_validated_whatsapp' => 'Cliente não possui WhatsApp validado',
    'whatsapp_validation_required_not_configured' => 'Validação WhatsApp necessária mas não configurada',
    'code_sent_to_whatsapp' => 'Código enviado para seu WhatsApp!',
    'whatsapp_validated_successfully' => 'WhatsApp validado com sucesso!',
    'invalid_code_try_again' => 'Código inválido. Tente novamente.',
    'not_verified' => 'Não Verificado',
    'not_registered' => 'Não cadastrado',
    'message_blocked_whatsapp_not_validated' => 'Mensagem bloqueada - WhatsApp não validado',
    'message_blocked_whatsapp_not_validated_colon' => 'Mensagem bloqueada: WhatsApp não validado',
    'whatsapp_validated_send_allowed' => 'WhatsApp validado - envio permitido',
    'whatsapp_validation_disabled' => 'Validação WhatsApp desabilitada',
    'enter_code_to_validate_whatsapp' => 'Digite este código na área do cliente para validar seu WhatsApp.\n\n',
    'sending' => 'Enviando...',
    'send_whatsapp_reminder' => 'Enviar Lembrete WhatsApp',
    'reminder_sent_successfully_to' => 'Lembrete enviado com sucesso para',
    'select_quick_reply' => '-- Selecione uma resposta rápida --',
    'type_message_to' => 'Digite sua mensagem para',
    'type_your_message_here' => 'Digite sua mensagem aqui...',
    'would_like_more_info' => 'Gostaria de mais informações',
    'would_like_more_info_punctuated' => '! Gostaria de mais informações.',
    'button_displayed' => 'Botão exibido',
    'no_return' => 'Sem Retorno',
    'pix_qr_code' => 'QR Code PIX',
    'details_updated' => 'Detalhes atualizados',
    'info_updated' => 'Informações atualizadas',
    'no_service' => 'Nenhum serviço',
    'no_domain' => 'Nenhum domínio',
    'other_reason' => 'Outro motivo',
    'no_longer_required' => 'Não é mais necessário',
    'going_to_competitor' => 'Migrando para concorrente',
    'too_expensive' => 'Muito caro',
    'technical_issues' => 'Problemas técnicos',
    'userid_not_found_in_vars' => 'UserChangePassword: userid não encontrado nos vars',
    'user_client_relation_not_found' => 'Relação usuário-cliente não encontrada para userid',
    'could_not_find_client_id' => 'Não foi possível encontrar client_id para o usuário ID',
    'template_password_changed_not_found' => 'Template password_changed não encontrado ou inativo',
    'client_id_label' => 'Cliente ID',
    'not_found' => 'não encontrado',
    'client_found' => 'Cliente encontrado',
    'phone_number_not_found_for_client' => 'Número de telefone não encontrado para cliente',
    'preparing_send' => 'Preparando envio',
    'error_sending_notification' => 'Erro ao enviar notificação',
    'detailed_exception' => 'Exception detalhada',
    'exception' => 'Exceção',
    'client_id_found_via_tblusers' => 'Client_id encontrado via tblusers',
    'client_id_found_via_tblusers_clients' => 'Client_id encontrado via tblusers_clients',
    'template_not_found_or_inactive' => 'Template não encontrado ou inativo',
    'module_disabled' => 'Módulo desabilitado',
    'service_id_label' => 'Service ID',
    'template_found' => 'Template encontrado',
    'service_not_found' => 'Serviço não encontrado',
    'client_number_label' => 'Número do cliente',
    'phone_number_not_found' => 'Número de telefone não encontrado',
    'validation_status_label' => 'Status de validação',
    'send_result_label' => 'Resultado do envio',
    'exception_caught' => 'Exceção capturada',
    'no_changes_detected' => 'Sem alterações detectadas',
    'changes_detected' => 'Alterações detectadas',
    'invoice_not_found' => 'Fatura não encontrada',
    'ticket_not_found' => 'Ticket não encontrado',
    'quote_not_found' => 'Cotação não encontrada',
    'variable_defined_as_empty' => 'Variável definida como vazia',
    'missing_required_variables' => 'Variáveis obrigatórias faltantes',
    'hook_triggered' => 'Hook disparado',
    'validation_scenarios' => 'Cenários de validação',
    'boleto_found' => 'Boleto encontrado',
    'pix_found' => 'PIX encontrado',
    'invoice_data' => 'Dados da fatura',
    'iugupix_raw_data' => 'Dados iugupix brutos',
    'final_extracted_data' => 'Dados extraídos FINAIS',
    'starting' => 'Iniciando',
    'image_sent' => 'Imagem enviada',
    'text_sent' => 'Texto enviado',
    'template_not_found_for_service' => 'Template não encontrado para serviço',
    'email_replaced_by_whatsapp' => 'Email substituído por WhatsApp',
    'client_add_hook_error' => 'ClientAdd Hook: ',
    'user_change_password_hook_error' => 'UserChangePassword Hook ERROR: ',
    'invoice_created_hook_error' => 'InvoiceCreated Hook: ',
    'invoice_paid_hook_error' => 'InvoicePaid Hook: ',
    'invoice_cancelled_hook_error' => 'InvoiceCancelled Hook: ',
    'invoice_payment_reminder_hook_error' => 'InvoicePaymentReminder Hook: ',
    'ticket_open_hook_error' => 'TicketOpen Hook: ',
    'ticket_admin_reply_hook_error' => 'TicketAdminReply Hook: ',
    'after_module_create_hook_error' => 'AfterModuleCreate Hook: ',
    'after_module_suspend_hook_error' => 'AfterModuleSuspend Hook: ',
    'after_module_unsuspend_hook_error' => 'AfterModuleUnsuspend Hook: ',
    'after_module_terminate_hook_error' => 'AfterModuleTerminate Hook: ',
    'cancellation_request_hook_error' => 'CancellationRequest Hook: ',
    'client_edit_hook_error' => 'ClientEdit Hook: ',
    'quote_created_hook_error' => 'QuoteCreated Hook: ',
    'quote_modified_hook_error' => 'QuoteModified Hook: ',
    'quote_accepted_hook_error' => 'QuoteAccepted Hook: ',
    'send_custom_message_hook_error' => 'SendCustomMessage Hook: ',
    'admin_area_client_summary_action_links_hook_error' => 'AdminAreaClientSummaryActionLinks Hook: ',
    'admin_invoices_controls_output_hook_error' => 'AdminInvoicesControlsOutput Hook: ',
    'email_presend_hook_error' => 'EmailPreSend Hook: ',
    'invoice_cancelled_invoice_not_found_prefix' => 'InvoiceCancelled: Fatura não encontrada - ',
    'quote_created_quote_not_found_prefix' => 'QuoteCreated: Cotação não encontrada - ',
    'quote_modified_quote_not_found_prefix' => 'QuoteModified: Cotação não encontrada - ',
    'quote_accepted_quote_not_found_prefix' => 'QuoteAccepted: Cotação não encontrada - ',
    'cancellation_request_service_id_not_provided' => 'CancellationRequest: ID do serviço não fornecido',
    'cancellation_request_service_not_found_prefix' => 'CancellationRequest: Serviço não encontrado - ',
    'error_getting_cancellation_data_prefix' => 'Erro ao obter dados de cancelamento: ',
    'error_preparing_quote_variables_prefix' => 'Erro ao preparar variáveis da cotação: ',
    'error_getting_payment_data_prefix' => 'Error getting payment data: ',
    'error_in_whatsapp_validation_prefix' => 'Erro na validação WhatsApp: ',
    'error_getting_client_variables_prefix' => 'Erro ao obter variáveis do cliente: ',
    'send_message_with_media_error_prefix' => 'send_message_with_media: ',
    'error_in_automatic_log_cleanup_prefix' => 'Erro na limpeza automática de logs: ',
    'validation_code_header' => '⚙️ *Código de Validação WhatsApp*\n\n',
    'your_validation_code_is' => 'Seu código de validação é:',
    'code_expires_24_hours' => 'Este código expira em 24 horas.',
    'whatsapp_validation_label' => 'Validação WhatsApp',

    // Auto Login - Geral
    'autologin_title' => 'Auto Login (use nos emails)',
    'autologin_subtitle' => 'Gerencie tokens de acesso direto para faturas e tickets',

    // Auto Login - Estatísticas
    'active_tokens' => 'Tokens Ativos',
    'expired_tokens' => 'Tokens Expirados',
    'used_tokens' => 'Tokens Usados',
    'used_today' => 'Usados Hoje',
    'active_tokens_desc' => 'tokens válidos e utilizáveis.',
    'expired_tokens_desc' => 'tokens que perderam validade.',
    'total_clicks_desc' => 'acessos gerados pelos tokens.',
    'total_tokens_desc' => 'quantidade total gerada.',

    // Auto Login - Tabela
    'tokens_history' => 'Histórico de Tokens',
    'type' => 'Tipo',
    'target' => 'Alvo',
    'token' => 'Token',
    'created_at' => 'Criado em',
    'expires_at' => 'Expira em',
    'used_at' => 'Usado em',
    'ip_address' => 'IP',
    'status' => 'Status',

    // Auto Login - Status
    'active' => 'Ativo',
    'expired' => 'Expirado',
    'used' => 'Usado',

    // Auto Login - Tipos
    'invoice' => 'Fatura',
    'ticket' => 'Ticket',

    // Auto Login - Variáveis de Template
    'link_fatura_autologin' => 'Link de Acesso Direto à Fatura',
    'link_ticket_autologin' => 'Link de Acesso Direto ao Ticket',
    'token_autologin' => 'Token de Acesso',
    'token_expiracao' => 'Expiração do Token',

    // MessageProcessor - Mensagens de erro e log
    'template_error_prefix' => 'Erro no Template: ',
    'client_variables_error_prefix' => 'Erro nas Variáveis do Cliente: ',
    'invoice_variables_error_prefix' => 'Erro nas Variáveis da Fatura: ',
    'ticket_variables_error_prefix' => 'Erro nas Variáveis do Ticket: ',
    'service_variables_error_prefix' => 'Erro nas Variáveis do Serviço: ',
    'quote_variables_error_prefix' => 'Erro nas Variáveis da Cotação: ',
    'message_split_into_parts' => 'Mensagem dividida em partes',
    'invoice_variables_prepared' => 'Variáveis de fatura preparadas',
    'qr_code_part_split' => 'Parte com QR Code dividida',

     // Admin & Hooks - Mensagens do sistema
    'connection_error_prefix' => 'Erro de conexão: ',
    'export_settings_error' => 'Erro ao exportar configurações',
    'token_copied_to_clipboard' => 'O token foi copiado para a área de transferência.',
    'send_code_error' => 'Erro ao enviar código',
    'user_change_password_userid_not_found' => 'UserChangePassword: userid não encontrado nos vars: ',
    'suspension' => 'Suspensão',
    'reactivation' => 'Reativação',
    'domain' => 'Domínio',
    'address' => 'Endereço',
    'request_error_prefix' => 'Erro na requisição: ',
    'confirm_validation' => 'Confirmar Validação',
    'send_validation_code_to_client' => 'Enviar código de validação para o cliente?',
    'validation_code_sent_success_short' => 'Código de validação enviado!',
    'priority_medium_icon' => '🟡 Média',
    'not_verified_icon' => '⚠️ Não Verificado',
    'service_number_prefix' => 'Serviço #',

    // Validação de WhatsApp - Interface
    'whatsapp_validation_subtitle' => 'Valide seu número para receber notificações importantes',
    'phone_number_label' => 'Número de WhatsApp',
    'phone_number_help' => 'Número cadastrado no WHMCS. Para alterar, atualize seu cadastro.',
    'send_code_button' => 'Enviar Código de Verificação',
    'change_phone_button' => 'Alterar Número',
    'verification_code_label' => 'Código de Verificação',
    'verification_code_help' => 'Digite o código de 6 dígitos enviado para seu WhatsApp',
    'code_expires_in_15_minutes' => 'Código expira em 15 minutos',
    'validate_code_button' => 'Validar Código',
    'back_to_change_phone' => 'Voltar / Corrigir Número',
    
    // Mensagens JavaScript
    'sending_code' => 'Enviando código...',
    'code_sent_title' => 'Código Enviado!',
    'code_sent_text' => 'Verifique seu WhatsApp e digite o código de 6 dígitos.',
    'validating_code' => 'Validando código...',
    'validation_success_title' => 'Validação Concluída!',
    'validation_success_text' => 'Seu WhatsApp foi validado com sucesso!',
    'error_title' => 'Erro',
    'code_expired_title' => 'Código Expirado',
    'code_expired_text' => 'O código de verificação expirou. Solicite um novo código.',
    'ok_button' => 'OK',
    'try_again' => 'Tentar Novamente',
    
    // Confirmações
    'confirm_change_phone' => 'Deseja corrigir o número?',
    'confirm_change_phone_text' => 'Você será redirecionado para alterar seu número no cadastro.',
    'yes_change' => 'Sim, corrigir',
    
    // Backend
    'code_expired' => 'Código expirado. Solicite um novo código.',
    'back_resend_button' => 'Voltar e Reenviar Código',

    // Gateways
    'gateways_subtitle_new' => 'Selecione o gateway de pagamento para extrair dados de PIX e Boleto',
    'how_to_create_gateway' => 'Como criar um gateway?',
    'no_gateways_found' => 'Nenhum gateway encontrado',
    'no_gateways_description' => 'Nenhum gateway foi encontrado na pasta gateways/. Crie seu primeiro gateway seguindo o tutorial.',
    'learn_how_to_create' => 'Aprenda como criar',
    'active_gateway' => 'Gateway Ativo',
    'none_selected' => 'Nenhum selecionado',
    'none_disabled' => 'Nenhum (desativado)',
    'no_gateway_description' => 'Não extrair dados de PIX/Boleto',
    'select_this_gateway' => 'Selecionar este gateway',
    'file' => 'Arquivo',
    'version' => 'Versão',
    'gateway_information' => 'Informações sobre Gateways',
    'how_it_works' => 'Como Funciona',
    'available_variables' => 'Variáveis Disponíveis',
    'var_codigopix' => 'Código PIX para pagamento',
    'var_qr_code_url' => 'URL da imagem do QR Code PIX',
    'var_linhadigitavel' => 'Linha digitável do boleto',
    'var_link_fatura' => 'Link para visualizar a fatura (PDF ou HTML)',
    'view_all_variables' => 'Ver todas as variáveis',
    'confirm_change_gateway' => 'Confirmar mudança de gateway?',
    'confirm_change_gateway_text' => 'Tem certeza que deseja alterar o gateway ativo? Isso afetará a extração de dados de PIX/Boleto.',
    'yes_change' => 'Sim, alterar',
    'cancel' => 'Cancelar',
    'success' => 'Sucesso',
    'error' => 'Erro',
    'unknown_error' => 'Erro desconhecido',
    'connection_error' => 'Erro de conexão com o servidor',
    'invalid_gateway' => 'Gateway inválido',
    'gateway_file_not_found' => 'Arquivo do gateway não encontrado',
    'gateway_deactivated_success' => 'Gateway desativado com sucesso',
    'gateway_activated_success' => 'Gateway ativado com sucesso:',
    'error_saving_gateway' => 'Erro ao salvar gateway',
    'file_none' => 'Nenhum arquivo.',

    // Tutorial Modal
    'tutorial_title' => 'Como Criar Seu Próprio Gateway',
    'close' => 'Fechar',
    'tutorial_full_docs' => 'Documentação Completa',

    // Passo 1
    'tutorial_step1_title' => 'Passo 1: Criar o Arquivo',
    'tutorial_step1_desc' => 'Crie um arquivo na pasta <code>/modules/addons/zapcel/gateways/</code> com o nome do seu gateway:',
    'tutorial_step1_ex1' => 'Mercado Pago → <code>MercadoPagoGateway.php</code>',
    'tutorial_step1_ex2' => 'Banco Inter → <code>BancoInterGateway.php</code>',
    'tutorial_step1_ex3' => 'PagHiper → <code>PagHiperGateway.php</code>',

    // Passo 2
    'tutorial_step2_title' => 'Passo 2: Estrutura Básica',
    'tutorial_step2_desc' => 'Cole este código no arquivo criado:',
    'tutorial_code_classname' => 'SeuGatewayGateway',
    'tutorial_code_gatewayname' => 'seugateway',
    'tutorial_code_comment_pix' => 'Buscar dados do PIX no banco',
    'tutorial_code_comment_boleto' => 'Buscar dados do Boleto no banco',
    'tutorial_code_table_pix' => 'sua_tabela_pix',
    'tutorial_code_table_boleto' => 'sua_tabela_boleto',

    // Passo 3
    'tutorial_step3_title' => 'Passo 3: Descobrir Tabelas e Campos',
    'tutorial_step3_desc' => 'Use phpMyAdmin ou MySQL para encontrar onde seu gateway salva os dados:',
    'tutorial_sql_comment1' => 'Listar tabelas do gateway',
    'tutorial_sql_comment2' => 'Ver estrutura da tabela',
    'tutorial_sql_comment3' => 'Ver dados de exemplo',

    // Passo 4
    'tutorial_step4_title' => 'Passo 4: Ativar o Gateway',
    'tutorial_step4_desc' => 'Após salvar o arquivo:',
    'tutorial_step4_item1' => 'Recarregue esta página',
    'tutorial_step4_item2' => 'Seu gateway aparecerá automaticamente na lista',
    'tutorial_step4_item3' => 'Selecione-o e clique em "Salvar"',
    'tutorial_step4_item4' => 'Pronto! O sistema começará a usar seu gateway',

    // Dicas
    'tutorial_tips_title' => 'Dicas Importantes',
    'tutorial_tip1' => 'Use <code>try-catch</code> para evitar erros',
    'tutorial_tip2' => 'Sempre retorne <code>null</code> se não houver dados',
    'tutorial_tip3' => 'Teste com uma fatura real antes de usar em produção',
    'tutorial_tip4' => 'Documente seu código para facilitar manutenção',

];